version: "3"
services:
  api:
    container_name: braviChallengeApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - pg
    command: bash -c 'yarn migration:run && yarn dev'
  pg:
    container_name: bravichallengedb
    image: postgres
    env_file:
      - .env
    expose:
      - 5432
    ports:
      - 5434:5432